apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone
  namespace: infra
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone-infra
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - services
  verbs:
  - get
  - create
  - delete
  - list
  - watch
  - update
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - create
  - delete
  - list
  - watch
  - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone
subjects:
- kind: ServiceAccount
  name: drone
  namespace: infra
roleRef:
  kind: ClusterRole
  name: drone-infra
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-runner
  namespace: infra
  labels:
    name: drone-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      name: drone-runner
  template:
    metadata:
      labels:
        name: drone-runner
    spec:
      serviceAccount: drone
      containers:
      - name: runner
        image: drone/drone-runner-kube:latest
        ports:
        - containerPort: 3000
        env:
        - name: DRONE_RPC_HOST
          value: drone
        - name: DRONE_RPC_PROTO
          value: http
        - name: DRONE_RPC_SECRET
          value: 3e5490b19f08c681d7407ff2f7ef3ec4